# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_postmodel_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='postimgs'),
        ),
    ]
