# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('followers', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('foto', models.ImageField(upload_to='amigos_fotos')),
                ('slug', models.SlugField()),
                ('cumpleanos', models.DateTimeField(db_index=True)),
            ],
        ),
    ]
