# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amigos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amigo',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
