# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amigos', '0002_auto_20171104_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='amigo',
            name='lugar_donde_nos_conocimos',
            field=models.CharField(blank=True, choices=[('escuela', 'escuela'), ('parque', 'parque'), ('fiesta', 'fiesta')], max_length=200, null=True),
        ),
    ]
